version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 6.20.15
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
  - dependency-name: facade/ignition
    versions:
    - 2.5.13
    - 2.5.14
    - 2.6.0
    - 2.7.0
    - 2.8.2
  - dependency-name: laravel/telescope
    versions:
    - 4.4.3
    - 4.4.4
    - 4.4.5
    - 4.4.6
    - 4.4.8
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.2
    - 9.5.3
  - dependency-name: nemiah/php-fints
    versions:
    - 3.1.0
  - dependency-name: nunomaduro/collision
    versions:
    - 3.2.0
  - dependency-name: spatie/laravel-cookie-consent
    versions:
    - 2.12.12
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: filp/whoops
    versions:
    - 2.9.2
  - dependency-name: calebporzio/parental
    versions:
    - 0.11.0
